config/routes.rb
Rails.application.routes.draw do
  
  get 'main/under_construction'
  resources :victimas, only: [:index,:show]
  resources :tweets
  resources :monstruos
  
  root 'tweets#default'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monstruo.rb
class Monstruo < ApplicationRecord
  has_many :victimas, dependent: :destroy
  has_many :tweets, dependent: :destroy

  default_scope -> { order :nombre }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :monstruo

end

app/models/victima.rb
class Victima < ApplicationRecord
    belongs_to :monstruo


    default_scope -> { order :nombre }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def under_construction
  end
end

app/controllers/monstruos_controller.rb
class MonstruosController < ApplicationController
  
  def index
  end

  def show
    @monstruo=Monstruo.find(params[:id])
     if @monstruo.tweets.empty?
       flash[:error]="ERROR AL CARGAR"
       redirect_to monstruos_path,
       status=>
          :found,
          :notice => "¡No se han encontrado twits para ese monstruo!"
          #,action=>"controllerName"
     end


  end

  def edit    
  end
  
  def destroy
    m=Monstruo.find(params[:id])
    m.destroy
    redirect_to monstruo_path
  end
end

app/controllers/tweets_controller.rb
# encoding = utf-8
class TweetsController < ApplicationController
  
  def new
  	@tweet = Tweet.new
  end

  def default    
  end
  
  def index
  end

  def show
  end

  # -----------------
  # CREATE
  # El método create recibe params = { tweet: { monstruo_id: valor, estado: valor } }
  def create

    # tweet.monstruo_id=params[:tweet][:monstruo_id]
    # tweet.estado=params[:tweet][:estado]
    # tweet.save
    # redirect_to root_path
    @tweet=Tweet.new(params.require(:tweet).permit(:monstruo_id,:estado))
    byebug
    if @tweet.save
      redirect_to root_path, notice: "Tweet creado exitosamente"
    else
      flash[:error]="ERROR AL CARGAR"
      render :new
    end
  end
end

app/controllers/victimas_controller.rb
class VictimasController < ApplicationController
  def index
    @victimas=Victima.all

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/victimas_helper.rb
module VictimasHelper
end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
          
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag "logo.png", title: "Logo", class: "navbar-brand" %>
            Critter
          <% end %>
        </div>
        <div class="collapse navbar-collapse">
          
        </div><!--/.nav-collapse -->
      </div>

    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Critter </title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container"> 
  
  <% if flash[:notice] %>
    <div class="alert alert-info"> <%= flash[:notice] %> </div>
  <% end %>
  
	<%= yield %>
</div>

</body>
</html>

app/views/main/under_construction.html.erb
<h1>Lo sentimos <%=link_to "Volver",root_path%></h1>

<img src="https://upload.wikimedia.org/wikipedia/commons/1/1e/SITIO-EN-CONSTRUCCION.jpg"
class="img-fluid">

app/views/monstruos/edit.html.erb
<h1> Editar monstruo </h1>

<p> No está hecho </p>

app/views/monstruos/index.html.erb
<h1> Listado de Monstruos </h1>

<table class="table">

	<tr>
		<th> Nombre </th>
		<th> Descripción </th>
		<th> Critter start </th>
		<th> Acciones </th>
	</tr>

	<% monstruos = Monstruo.all %>
	<% monstruos.each do |monstruo| %>
		<tr>
			<td> <%= link_to monstruo.nombre, monstruo %> </td>
			<td> <%= monstruo.descripcion %> </td>
			<td> <%= (monstruo.critter_star) ? 'Si' : 'No' %> </td>
			<td>
				<%= link_to "Editar", edit_monstruo_path(monstruo), class: 'btn btn-info btn-sm' %>
				<%= link_to "Eliminar",
				 monstruo,
				  method: :delete,
				  data:{confirm: "Segurx?"},
				  class: 'btn btn-danger btn-sm'
				  %>
			</td>
		</tr>
	<% end %>

	<% if monstruos.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

app/views/monstruos/show.html.erb
<div class="container">
    <div class="card" style="width: 50rem;">
        <div class="card-header">
            <h1><%=@monstruo.nombre%></h1>
            <h3> <%=@monstruo.descripcion%>  </h3>
        </div>
        <div class="card-body">
            <h3 class="card-title">Tweets de <%=@monstruo.nombre%></h3>
        
            <%@monstruo.tweets.each do |t|%>
                <p class="list-group-item"> <b><i> <%=t.estado%></i> </b> </p>
            <%end%>
            <%=link_to "Volver",monstruos_path%>
            <!---
            <%if @monstruo.tweets.empty?%>
                <p> No se han encontrado monstruos </p>
            <%end%>
            --->
        </div>
    </div>
</div>

app/views/monstruos/ver.html.erb
<!------------------------------------------------------ 
Debe mostrarse la información del primer monstruo sin
usar el id.
Se debe mostrar el nombre (como título) y la descripción 
(como párrafo).
------------------------------------------------------>

HACER <br>
/app/views/monstruos/ver.html.erb

app/views/tweets/default.html.erb
<h1> Bienvenido a Critter </h1>
<h3> ¿Qué desea hacer? </h3>
<ul>
  <li> <%= link_to "Nuevo Tweet", new_tweet_path %></li>
  <li> <%= link_to "Listado de Monstruos", monstruos_path %></li>  
  <li> <%= link_to "Listado de Victimas", victimas_path %></li>  
  <li> <%= link_to "Futura ayuda", main_under_construction_path %></li> 
</ul>

app/views/tweets/index.html.erb
<!-- Listado de tweets -->

app/views/tweets/new.html.erb
<div class="container">
	<h1> Crear un tweet para un monstruo </h1>

	<%= form_for @tweet do |f| %>
		
		<div class="row">
			<div class="col-md-4">
				<%= f.label :monstruo_id, 'Monstruo' %>
  				<%= collection_select(:tweet, :monstruo_id, Monstruo.all, :id, :nombre, {}, { class: 'form-control'}) %>
  			</div>
  		</div>


		<div class="row">
			<div class="col-md-6">
				<%= f.label :estado %>
  				<%= f.text_area :estado, class: 'form-control', label: 'Estado', placeholder: 'Ingrese el estado' %>
  			</div>
  		</div>

  		<%= f.submit "Crear tweet", class: 'btn btn-primary' %>
  	</div>
<% end %>
</div>

app/views/tweets/show.html.erb
<!-- Ver un tweet -->
Detalle del tweet

app/views/victimas/index.html.erb
<h1> Listado de victimas! </h1>
<table class="table">

	<tr>
		<th> Nombre </th>
		<th> Edad </th>
		<th> Monstruo </th>
	</tr>

	<% @victimas.each do |vic| %>
		<tr>
			<td> <%= link_to vic.nombre, victimas_path %> </td>
			<td> <%= vic.edad %> </td>
			<td> <%=vic.monstruo.nombre%> </td>
		</tr>
	<% end %>

	<% if @victimas.size == 0 %>
		<tr> <td colspan="3"> No hay monstruos </td> </tr>
	<% end %>

</table>

app/views/victimas/show.html.erb
<h1>Victimas#show</h1>
<p>Find me in app/views/victimas/show.html.erb</p>